#1_borris123_test

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -1,11 +1,3 @@
-# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
-
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-
 name: Java CI with Maven
 
 on:
@@ -27,31 +19,36 @@ jobs:
           MYSQL_PASSWORD: test_password
         ports:
           - 3306:3306
+
     steps:
-    - uses: actions/checkout@v4
-    - name: Set up JDK 17
-      uses: actions/setup-java@v4
-      with:
-        java-version: '21'
-        distribution: 'temurin'
-        cache: maven
+      - uses: actions/checkout@v4
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '21'
+          distribution: 'temurin'
+          cache: maven
 
-    - name: Wait for MariaDB to be ready
-      run: |
-        for i in {1..3}; do
-          if mysqladmin ping -h "localhost" --user=test_user --password=test_password --silent; then
-            echo "MariaDB is ready!"
-            break
-          fi
-          echo "Waiting for MariaDB..."
-          sleep 5
-        done
+      - name: Wait for MariaDB to be ready
+        run: |
+          for i in {1..3}; do
+            if mysqladmin ping -h "mariadb" --user=test_user --password=test_password --silent; then
+              echo "MariaDB is ready!"
+              break
+            fi
+            echo "Waiting for MariaDB..."
+            sleep 5
+          done
 
-    - name: Build with Maven
-      run: mvn -B package --file pom.xml
+      - name: Check MariaDB connection
+        run: |
+          mysql -h mariadb -u test_user -p 'test_password' -e 'SELECT 1;' || { echo "Database connection failed!"; exit 1; }
 
-    - name: Run Tests
-      run: mvn -B test --file pom.xml
+      - name: Build with Maven
+        run: mvn -B package --file pom.xml
 
-    - name: Update dependency graph
-      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
+      - name: Run Tests
+        run: mvn -B test --file pom.xml
+
+      - name: Update dependency graph
+        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
